name: Deploy

on:
  push:
    branches: main

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email "rrcjadework@gmail.com"
          git config --global user.name "rcRen"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create env file
        run: |
          if [ ! -f ".env" ]; then
            touch .env
            echo "REACT_APP_SANITY_PROJECT_ID=${{ secrets.REACT_APP_SANITY_PROJECT_ID}}" >> .env
            echo "REACT_APP_SANITY_DATASET=${{ secrets.REACT_APP_SANITY_DATASET }}" >> .env
            echo "REACT_APP_SANITY_APPLICATION_TOKEN=${{ secrets.REACT_APP_SANITY_APPLICATION_TOKEN }}" >> .env
          fi
      - name: Install dependencies
        run: |
          npm install
      - name: Deploy
        run: npm run deploy
